services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - GENERIC_TIMEZONE=Europe/Madrid
      - NODE_ENV=production
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./shared:/shared

  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION:-latest}
    ports:
      - "8025:8025"

volumes:
  n8n_data:
